import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./Provider";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const MyAppFont = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AMGT - AI Stories for kids",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={MyAppFont.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
